#!/usr/bin/env bash
# Declared-wait, decision and bounded busy-state watcher regressions.
# Case definitions and fixtures have one owner in watch-triage-helpers.sh.
# Separate serial CI units retain every case inside the per-script bound.
set -u

# shellcheck source=tests/watch-triage-helpers.sh
. "$(dirname "${BASH_SOURCE[0]}")/watch-triage-helpers.sh"

test_status_is_paused_classifier
test_explicit_decision_view_preserves_the_durable_fold
test_parked_decision_survives_pane_repaint
test_resolved_decision_can_reopen_identically
test_new_keyed_decision_on_parked_pane_surfaces
test_parked_decision_with_dead_agent_wedge_escalates
test_busy_pane_progressing_run_holds_then_escalates_past_the_cap
test_busy_pane_below_turn_age_bound_is_absorbed
test_busy_pane_stable_hash_escalates_past_turn_age_bound
test_busy_pane_changing_hash_escalates_past_turn_age_bound
test_busy_pane_turn_end_touch_resets_age
test_busy_pane_repeated_escalation_reaches_demand_deep_inspection
test_busy_pane_default_turn_age_bound_is_3600s
test_busy_declared_pause_is_rechecked_not_wedge_escalated
test_afk_busy_declared_pause_hands_off_plain_stale
test_afk_busy_declared_pause_ticking_pane_hands_off_once
test_nonterminal_stale_paused_absorbed_then_resurfaced
test_pause_resurface_window_backs_off_and_caps
test_pause_streak_bump_reconciles_a_changed_wait
test_paused_resurface_backs_off_while_wedge_still_escalates
test_exited_declared_pause_is_bounded_but_live_captain_held_surfaces
test_live_declared_pause_is_absorbed_on_the_designed_cadence
test_declared_pause_landing_mid_classification_never_emits_a_bare_stale
test_live_declared_pause_still_recoverable_once_its_agent_dies
test_absorbed_replacement_wait_does_not_inherit_the_old_throttle
test_live_declared_wait_churn_honors_the_resurface_throttle
test_open_captain_call_bounds_stale_churn
test_stale_churn_without_a_captain_call_still_alarms
test_reheld_captain_call_starts_its_own_resurface_window
test_secondmate_paused_resurfaces_in_normal_mode
test_secondmate_nonpaused_stale_remains_suppressed
test_secondmate_unpause_clears_pause_tracking
test_nonterminal_stale_pause_transitions_reclassify_unchanged_hash
test_nonterminal_paused_rechecks_authoritative_state
test_paused_authoritative_working_preserves_wedge_timer
test_afk_paused_changed_pane_hands_off_plain_stale
test_live_paused_until_controls_recheck_time

test_paused_until_near_future_is_quiet_before_the_cadence

test_paused_until_wrong_year_is_bounded_by_the_cadence

test_paused_until_that_passed_is_rechecked_before_the_cadence

printf '\nall fm-watch-triage-waits tests passed\n'
